export const images = [
  {
    src: require(`./images/image1.jpg`),
    title: "Pavouk v síti",
    species: "Australian garden orb weaver spider (Eriophora transmarina)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image2.jpg`),
    title: "Kusadla",
    species: "Australian garden orb weaver spider (Eriophora transmarina)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image3.jpg`),
    title: "Cikáda na kmeni",
    species: "Cikáda (Cicada spp.)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image4.jpg`),
    title: "Silueta šídla",
    species: "Šídlo (Aeshnidae spp.)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image5.jpg`),
    title: "Ježura zblízka",
    species: "Ježura australská (Tachyglossus aculeatus)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image6.jpg`),
    title: "Klokan nenápadný",
    species: "Klokan nenápadný (Petrogale mareeba)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image7.jpg`),
    title: "Bradavičník arafurský",
    species: "Bradavičník arafurský (Acrochordus arafurae)",
    location: "Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image8.jpg`),
    title: "Lori horský",
    species: "Lori horský (Trichoglossus moluccans)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image9.jpg`),
    title: "Ledňák obrovský",
    species: "Ledňák obrovský (Dacelo novaeguineae)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image10.jpg`),
    title: "Žabí oko",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image11.jpg`),
    title: "Mravenec",
    species: "Bulldog ant (Myrmecia spp.)",
    location: "Dinden National Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image12.jpg`),
    title: "Žába v dešti",
    species: "Rosnice siná (Litoria caerulea)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image13.jpg`),
    title: "Svlečená cikáda",
    species: "Cikáda (Macrotristria intersecta)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image14.jpg`),
    title: "Strašilka australská",
    species: "Strašilka australská (Extatosoma tiaratum)",
    location: "Mungumby Lodge, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image15.jpg`),
    title: "Žába na kameni",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Mungumby Lodge, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image16.jpg`),
    title: "Rosnička žlutoboká",
    species: "Rosnička žlutoboká (Ranoidea xanthomera)",
    location: "Mungumby Lodge, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image17.jpg`),
    title: "Krajta kobercová",
    species: "Krajta kobercová (Morelia spilota)",
    location: "Black Mountain, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image18.jpg`),
    title: "Žabí romance",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Cooktown, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image19.jpg`),
    title: "Bělásek",
    species: "Red-banded Jezebel (Delias mysis)",
    location: "Crater Lakes, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image20.jpg`),
    title: "Kasuár přilbový",
    species: "Kasuár přilbový (Casuarius casuarius)",
    location: "Etty bay beach, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image21.jpg`),
    title: "Tabon lesní",
    species: "Tabon lesní (Alectura lathami)",
    location: "Canopy Treehouses, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image22.jpg`),
    title: "Lesní drak",
    species: "Agama pralesní (Lophosaurus boydii)",
    location: "Crater lakes, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image23.jpg`),
    title: "Maskovaná žába",
    species: "Cogger's Barred Frog (Mixophyes coggeri)",
    location: "Crater Lakes, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image24.jpg`),
    title: "Pagekon lupenoocasý",
    species: "Pagekon lupenoocasý (Saltuarius cornutus)",
    location: "Lake Barrine, Queensland, Austrálie",
    link: "",
    price: "",
  },
  {
    src: require(`./images/image25.jpg`),
    title: "Duhová mandelinka",
    species: "Mandelinka (Spilopyra spp.)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    link: "",
    price: "",
  },
];
