import { PhotoItem } from "../../types";

export const images = [
  {
    type: "photo",
    src: require(`./images/image1.jpg`),
    title: "Silueta šídla",
    species: "Šídlo (Aeshnidae spp.)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image2.jpg`),
    title: "Svlečená cikáda",
    species: "Cikáda (Macrotristria intersecta)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "500Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image3.jpg`),
    title: "Cikáda na kmeni",
    species: "Cikáda (Cicada spp.)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image4.jpg`),
    title: "Lesní drak",
    species: "Agama pralesní (Lophosaurus boydii)",
    location: "Crater lakes, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "500Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image5.jpg`),
    title: "Pagekon lupenoocasý",
    species: "Pagekon lupenoocasý (Saltuarius cornutus)",
    location: "Lake Barrine, Queensland, Austrálie",
    lens: "Sony FE 90mm f/2,8 G ",
    camera: "Sony Alpha A7 IV",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
] satisfies PhotoItem[];
