export const images = [
  {
    src: require(`./images/image1.jpg`),
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    link: "https://kachull4.gumroad.com/l/vyrvelkyportret",
    price: "250Kč",
  },
  {
    src: require(`./images/image2.jpg`),
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    link: "https://kachull4.gumroad.com/l/vyrvelky",
    price: "250Kč",
  },
  {
    src: require(`./images/image3.jpg`),
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    link: "https://kachull4.gumroad.com/l/vyrvelkyvletu",
    price: "250Kč",
  },
  {
    src: require(`./images/image4.jpg`),
    title: "Orel skalní",
    species: "Orel skalní (Aquila chrysaetos)",
    location: "Praha",
    link: "https://kachull4.gumroad.com/l/orelskalniportret",
    price: "250Kč",
  },
  {
    src: require(`./images/image5.jpg`),
    title: "Zajíc na hraně světa",
    species: "Zajíc polní (Lepus europaeus)",
    location: "Kounice",
    link: "https://kachull4.gumroad.com/l/zajicnahranesveta",
    price: "250Kč",
  },
];
