import { PhotoItem } from "../../types";

export const images = [
  {
    type: "photo",
    src: require(`./images/image1.jpg`),
    title: "Maskovaná žába",
    species: "Cogger's Barred Frog (Mixophyes coggeri)",
    location: "Crater Lakes, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "500Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image2.jpg`),
    title: "Žába v dešti",
    species: "Rosnice siná (Litoria caerulea)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image3.jpg`),
    title: "Žabí romance",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Cooktown, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image4.jpg`),
    title: "Bradavičník arafurský",
    species: "Bradavičník arafurský (Acrochordus arafurae)",
    location: "Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image5.jpg`),
    title: "Žabí oko",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image6.jpg`),
    title: "Rosnička žlutoboká",
    species: "Rosnička žlutoboká (Ranoidea xanthomera)",
    location: "Mungumby Lodge, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image7.jpg`),
    title: "Kukadla",
    species: "Kočka domácí bristská modrá (Felis catus)",
    location: "Kounice",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 35mm f/1,4 GM ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image8.jpg`),
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image9.jpg`),
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    type: "photo",
    src: require(`./images/image10.jpg`),
    title: "Zajíc na hraně světa",
    species: "Zajíc polní (Lepus europaeus)",
    location: "Kounice",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
] satisfies PhotoItem[];
