export const images = [
  {
    src: require(`./images/image1.jpg`),
    title: "Maskovaná žába",
    species: "Cogger's Barred Frog (Mixophyes coggeri)",
    location: "Crater Lakes, Queensland, Austrálie",
    price: "500Kč",
  },
  {
    src: require(`./images/image2.jpg`),
    title: "Žába v dešti",
    species: "Rosnice siná (Litoria caerulea)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    price: "250Kč",
  },
  {
    src: require(`./images/image3.jpg`),
    title: "Žabí romance",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Cooktown, Queensland, Austrálie",
    price: "250Kč",
  },
  {
    src: require(`./images/image4.jpg`),
    title: "Bradavičník arafurský",
    species: "Bradavičník arafurský (Acrochordus arafurae)",
    location: "Queensland, Austrálie",
    price: "250Kč",
  },
  {
    src: require(`./images/image5.jpg`),
    title: "Žabí oko",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    price: "250Kč",
  },
  {
    src: require(`./images/image6.jpg`),
    title: "Rosnička žlutoboká",
    species: "Rosnička žlutoboká (Ranoidea xanthomera)",
    location: "Mungumby Lodge, Queensland, Austrálie",
    price: "250Kč",
  },
  {
    src: require(`./images/image7.jpg`),
    title: "Kukadla",
    species: "Kočka domácí bristská modrá (Felis catus)",
    location: "Kounice",
    price: "250Kč",
  },
  {
    src: require(`./images/image8.jpg`),
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    price: "250Kč",
  },
  {
    src: require(`./images/image9.jpg`),
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    price: "250Kč",
  },
  {
    src: require(`./images/image10.jpg`),
    title: "Zajíc na hraně světa",
    species: "Zajíc polní (Lepus europaeus)",
    location: "Kounice",
    price: "250Kč",
  },
];
