import { PhotoItem } from "../../types";
import image1 from "./images/image1.jpg";
import image2 from "./images/image2.jpg";
import image3 from "./images/image3.jpg";
import image4 from "./images/image4.jpg";
import image5 from "./images/image5.jpg";
import image6 from "./images/image6.jpg";
import image7 from "./images/image7.jpg";
import image8 from "./images/image8.jpg";
import image9 from "./images/image9.jpg";
import image10 from "./images/image10.jpg";

export const images = [
  {
    id: "maskovana-zaba",
    type: "photo",
    src: image1,
    title: "Maskovaná žába",
    species: "Cogger's Barred Frog (Mixophyes coggeri)",
    location: "Crater Lakes, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "500Kč",
    availability: "available",
  },
  {
    id: "zaba-v-desti",
    type: "photo",
    src: image2,
    title: "Žába v dešti",
    species: "Rosnice siná (Litoria caerulea)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "zabi-romance",
    type: "photo",
    src: image3,
    title: "Žabí romance",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Cooktown, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "bradavicnik-arafursky",
    type: "photo",
    src: image4,
    title: "Bradavičník arafurský",
    species: "Bradavičník arafurský (Acrochordus arafurae)",
    location: "Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "zabi-oko",
    type: "photo",
    src: image5,
    title: "Žabí oko",
    species: "Rosnice běloretá (Litoria infrafrenata)",
    location: "Granite Gorge Nature Park, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "rosnicka-zlutoboka",
    type: "photo",
    src: image6,
    title: "Rosnička žlutoboká",
    species: "Rosnička žlutoboká (Ranoidea xanthomera)",
    location: "Mungumby Lodge, Queensland, Austrálie",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 90mm f/2,8 G ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "kukadla",
    type: "photo",
    src: image7,
    title: "Kukadla",
    species: "Kočka domácí bristská modrá (Felis catus)",
    location: "Kounice",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 35mm f/1,4 GM ",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "vyr-velky-1",
    type: "photo",
    src: image8,
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "vyr-velky-2",
    type: "photo",
    src: image9,
    title: "Výr velký",
    species: "Výr velký (Bubo Bubo)",
    location: "Praha",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
  {
    id: "zajic-na-hrane-sveta",
    type: "photo",
    src: image10,
    title: "Zajíc na hraně světa",
    species: "Zajíc polní (Lepus europaeus)",
    location: "Kounice",
    camera: "Sony Alpha A7 IV",
    lens: "Sony FE 200-600mm f/5,6-6,3 G OSS",
    resolution: "7008 × 4672",
    price: "250Kč",
    availability: "available",
  },
] satisfies PhotoItem[];
